### ISSUE TITLE
No Fullscreen on iOS?

### ISSUE THREAD

**Issue by boehser-enkel** [dermotduffy/advanced-camera-card#125]
**Checklist:**

- [X ] I updated to the latest version available
- [X ] I cleared the cache of my browser

**Release with the issue:**
1.2.0
**Last working release (if known):**
Version before
**Browser and Operating System:**
iOS 15.0.2, HA App 2021.8

**Description of problem:**
No Fullscreen view on IOS possible. Before it was a video player view with fullscreen and PIP buttons as usual. Now its gone. Also the fullscreen button (which i see in browser - this would be a workaround) is not visible.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by dermotduffy** [comment]
[The fullscreen view is not supported on iOS](https://github.com/dermotduffy/frigate-hass-card#fullscreen-button-does-not-appear-on-iphone) because iOS does not support the Javascript fullscreen API.  As such, the 'card-specific' button won't appear (as it _can't_ work).

With that said, this is not a _change_ in behavior, and you appear to be describing something different previously? Perhaps you're saying the video player itself (not the card) used to have a fullscreen button, and no-longer does?

**Comment by boehser-enkel** [comment]
Expected behaviour (like before): seeing a Video Player image with buttons for fullscreen, pip and stretch (the usual iOs video player)
Getting: a picture with no possibility to view it fullscreen.

Maybe you could add an extra button for iOs fullscreen? Maybe just view the camera entity (which supports fullscreen view)

**Comment by boehser-enkel** [comment]
Yes it was the iOs App for sure. Maybe it changed with iOs 15.0.2?

**Comment by boehser-enkel** [comment]
I dont get it...now its back? Without any change...
![Bild](https://user-images.githubusercontent.com/59539881/137442240-3f16f03c-daf4-463a-95a2-138326c722d7.png)

**Comment by dermotduffy** [comment]
Not sure why that would happen, but feels more like it's something on the  browser side: The card has no direct control of those 'in-video' buttons --  that's all the browser. The card could conceivably influence when the browser elects to show them, though -- but since you have a live example of them working, without any changes to the card, seems to more suggest the browser was electing not to show them previously for some reason.
